/**
 * The saved transcription run — what is worth keeping between sittings.
 *
 * Everything this app does is free except one step. Rendering, OCR, the
 * lexicon, assembly, layout and the PDF all cost nothing but time and can be
 * redone at will. The vision pass costs the user real money, once, per page.
 * So that is the only thing persisted: **the expensive output, keyed to the
 * file it came from.** Reopening the same book re-runs the free half and skips
 * the paid half.
 *
 * Deliberately *not* stored:
 *
 * - **The PDF itself.** A scan runs to hundreds of megabytes and the user
 *   already has it. Requiring it back on resume costs them one file picker and
 *   buys full fidelity: the word crops and page thumbnails the review gates
 *   show are regenerated by the free pass, so nothing is missing.
 * - **The API key.** It lives in its own store and must never travel with a
 *   book (see `platform/browser/settings`).
 * - **Anything derivable.** The assembled document, the findings summary, the
 *   layout — all pure functions of the transcriptions, so storing them would
 *   only create a second copy that could disagree with the first.
 *
 * Pure: types, versioning and migration. The store is in the platform layer.
 */
import { BLOCK_KINDS, type PageTranscription } from '@core/transcribe'
import type { BookEdit } from '@core/edits'
import { normalizeMarkup } from '@core/transcribe'
import type { ImageEditOp } from '@core/model'
import { FOOTINGS, type Fact } from '@core/harvest'
import { RULING_DECISIONS, type Ruling } from '@core/queries'
import { EDITORIAL_QUERY_KINDS } from '@core/transcribe'

/**
 * Current schema version. Bump and extend `migrateSavedRun` on any shape change.
 *
 * Versions 1–4 were the desktop application's `project.json` — a manifest of
 * page images, a Markdown intermediate, a coordinate map and non-destructive
 * image edits, none of which the browser app produces. Nothing ever wrote one
 * from a browser, so this does not migrate them; it recognises them and says so.
 *
 * v5 → v6 added the proofreading corrections, v6 → v7 the pixels of any
 * pictures the editor supplied, v7 → v8 whether the paid pass reached the end,
 * v8 → v9 what the second reading concluded about the flagged spots, and
 * v9 → v10 the fact bank this book produced, v10 → v11 `leafCount`, how
 * long the book actually is, v11 → v12 the editor's rulings on the queries
 * the reading raised, and v12 → v13 the `insert` edit, a block the editor wrote
 * standing inside the body rather than before or after it. None of them damages an older run — each is a complete transcription that simply
 * has none of the newer thing on it yet — so all upgrade in place rather than
 * being refused. That distinction is the whole reason a migration exists
 * instead of a version check.
 */
export const CURRENT_SCHEMA_VERSION = 13

/** A page the model could not read at all. Mirrors the runner's `PageFailure`. */
export interface SavedFailure {
  pageIndex: number
  message: string
}

/** Tokens spent, so the resume offer can say what re-running would cost again. */
export interface SavedUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
}

export interface SavedRun {
  schemaVersion: number
  /** Identifies the file this run belongs to — see `fileKey`. */
  key: string
  /** For showing the user which book this is. */
  fileName: string
  /** ISO timestamp, so the offer can say how old the run is. */
  savedAt: string
  pageCount: number
  /** The expensive part. */
  transcriptions: PageTranscription[]
  failures: SavedFailure[]
  usage: SavedUsage
  /** The model that read the pages, for the record. */
  modelId: string
  /**
   * The identity gate's answers, kept because they *shaped* this run — the
   * orthography choice and the long-s decision went into the prompt. Restoring
   * them stops the user silently changing an answer that can no longer take
   * effect on text the model has already produced.
   */
  identityAnswers: Record<string, unknown>
  /**
   * Corrections made at the proof step.
   *
   * Stored for the same reason the transcription is: they are the other thing
   * in this app the user cannot get back for free. Everything else — the
   * render, the OCR, the lexicon, the assembly, the layout — is regenerated
   * from the scan on the way back in, but an hour spent reading a book against
   * its scan is an hour, and a refresh must not cost it.
   */
  edits: BookEdit[]
  /**
   * Pixels for the pictures the editor supplied, by illustration id.
   *
   * Unlike everything else about an illustration, these cannot be re-derived
   * from anything the app has: a crop can be cut out of the scan again, but a
   * portrait the editor chose off their own disk is gone with the tab. Stored
   * as bytes because IndexedDB clones a `Uint8Array` natively, and bounded at
   * decode time so a phone photograph does not fill the store on its own.
   */
  images: { id: string; bytes: Uint8Array }[]
  /**
   * How many leaves the scan has — **0 when nobody knows**.
   *
   * Beside `pageCount` rather than replacing it, because the two halves of this
   * codebase had been writing `pageCount` to mean different things and there is
   * no way to tell afterwards which a stored record meant. The wizard writes
   * `transcriptions.length` there when it checkpoints a partial reading — how
   * many leaves have been *read* — while the driver and the shelf read it as
   * the length of the book. Nothing warned, because both are plausible numbers
   * of the same magnitude.
   *
   * That ambiguity is only harmless until something *decides* on it. Landing a
   * batch against a checkpointed run took the read count for the book's length
   * and reported `complete: true, stillMissing: 0` over sixteen leaves of a
   * three-hundred-leaf book — and refused correctly-numbered batches with a
   * message blaming the caller for counting from 1.
   *
   * So this field means one thing and says so, and a record written before it
   * existed migrates to **0 — unknown** rather than to whatever `pageCount`
   * happened to hold. Guessing there would bake the ambiguity in permanently,
   * and unknown is a state everything downstream already handles.
   */
  leafCount: number
  /**
   * Whether the paid pass reached the end of the book.
   *
   * The difference between "this book has been read" and "these pages have been
   * paid for" — and until v8 the store could not tell them apart, because
   * nothing was written until the whole run finished. A tab that died at page
   * 180 of 300 left nothing at all.
   *
   * A run is now checkpointed as it goes, so a partial one is the normal
   * intermediate state rather than a corruption. It resumes *transcription*
   * from where it stopped; a complete one skips straight past the paid step.
   * Getting this backwards costs real money in one direction and silently
   * prints a book missing its last hundred pages in the other.
   */
  complete: boolean
  /**
   * What the second reading concluded, keyed by discrepancy row id.
   *
   * Stored for the same reason the transcription is: it cost money. Losing it
   * would mean paying twice to be told the same thing about the same spots —
   * and unlike the reading of a scan, no amount of local work reproduces it.
   *
   * Additive, so a run written before this existed restores with none of it and
   * behaves exactly as it did: the gate shows every spot unchecked, which is
   * what it did before the pass existed at all.
   */
  adjudicated: Record<string, { verdict: string; reading: string; note: string }>
  /**
   * What the book was worth remembering — the fact bank, as the pass produced it.
   *
   * Stored for the plainest of reasons: it was paid for. Until v10 these lived
   * in a React state variable and were offered as two downloads on the export
   * screen, so anyone who closed the tab without pressing those buttons had
   * bought a file that no longer existed. Nothing about the printed book
   * depends on them, which is exactly why they were easy to forget.
   */
  facts: Fact[]
  /**
   * What the editor decided about the queries this reading raised.
   *
   * Here rather than in a file of its own for the reason the fact bank is: the
   * run is what the book file carries and what IndexedDB keeps, so anything
   * stored anywhere else is something a second device does not have. Until v12
   * a ruling existed only in the session that made it — the question reached
   * the shelf and the answer did not, so a later session would raise it again
   * and the introduction had to be told from memory what the edition decided.
   *
   * Additive, like every field before it: a run written under v11 restores with
   * none and behaves exactly as it did, which is every query still waiting.
   */
  rulings: Ruling[]
}

/** The facts the resume question needs, without loading the whole run. */
export interface SavedRunSummary {
  key: string
  fileName: string
  /** False when the paid pass stopped partway and can be continued. */
  complete: boolean
  savedAt: string
  pageCount: number
  failedPages: number
  modelId: string
  usage: SavedUsage
}

export function summarize(run: SavedRun): SavedRunSummary {
  return {
    key: run.key,
    fileName: run.fileName,
    complete: run.complete,
    savedAt: run.savedAt,
    pageCount: run.pageCount,
    failedPages: run.failures.length,
    modelId: run.modelId,
    usage: run.usage
  }
}

/**
 * A stable identity for the file a run belongs to.
 *
 * Name, size and modification time — not a hash of the contents. Hashing would
 * mean reading a few hundred megabytes into memory to answer a question that
 * only ever means "is this the same file the user had open before", and this
 * codebase is careful never to hold a whole book at once. The cost of being
 * wrong is small in both directions: a false miss offers a re-run the user can
 * decline, and a false hit is not reachable without deliberately crafting a
 * different file with an identical name, size and timestamp.
 */
export function fileKey(file: { name: string; size: number; lastModified: number }): string {
  // NUL joins the parts because it is the one byte a file name cannot
  // contain, so no name can be crafted to collide with a different file.
  return [file.name, file.size, file.lastModified].join('\u0000')
}

/**
 * Take a key apart again.
 *
 * The key is built from three facts about the file, so it can be read back into
 * them — which is what lets a run be found when one of the three has moved.
 * Returns null for anything not shaped like a key.
 */
export function parseFileKey(
  key: string
): { name: string; size: number; lastModified: number } | null {
  const parts = key.split('\u0000')
  if (parts.length !== 3) return null
  const size = Number(parts[1])
  const lastModified = Number(parts[2])
  if (!Number.isFinite(size) || !Number.isFinite(lastModified)) return null
  return { name: parts[0]!, size, lastModified }
}

/**
 * Whether a stored key plausibly belongs to this file, ignoring its timestamp.
 *
 * The exact key is tried first everywhere this is used; this is the fallback,
 * and it exists because the timestamp is the one of the three parts that moves
 * for reasons that have nothing to do with the book. Re-downloading the same
 * PDF, restoring it from a backup, or syncing it between devices all change the
 * modification time and none of them change a byte of the file.
 *
 * Name *and* size together, never name alone: two different scans of the same
 * title share a name constantly, and handing back the wrong book's
 * transcription would be worse than asking the user to pay again.
 */
export function keyMatchesFile(key: string, file: { name: string; size: number }): boolean {
  const parsed = parseFileKey(key)
  return parsed !== null && parsed.name === file.name && parsed.size === file.size
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function num(v: unknown, fallback: number): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback
}

function str(v: unknown, fallback: string): string {
  return typeof v === 'string' ? v : fallback
}

/** Build a run record from a finished transcription. */
export function createSavedRun(init: {
  key: string
  fileName: string
  pageCount: number
  /** How long the book is, 0 when unknown. See `SavedRun.leafCount`. */
  leafCount?: number
  transcriptions: readonly PageTranscription[]
  failures: readonly SavedFailure[]
  usage: SavedUsage
  modelId: string
  identityAnswers: Record<string, unknown>
  edits?: readonly BookEdit[]
  images?: ReadonlyMap<string, Uint8Array>
  savedAt?: string
  /** Defaults true: a caller that does not say is finishing a book, not checkpointing one. */
  complete?: boolean
  adjudicated?: Record<string, { verdict: string; reading: string; note: string }>
  facts?: readonly Fact[]
  rulings?: readonly Ruling[]
}): SavedRun {
  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    key: init.key,
    fileName: init.fileName,
    savedAt: init.savedAt ?? new Date().toISOString(),
    pageCount: init.pageCount,
    leafCount: init.leafCount ?? 0,
    transcriptions: [...init.transcriptions],
    failures: [...init.failures],
    usage: init.usage,
    modelId: init.modelId,
    identityAnswers: init.identityAnswers,
    edits: [...(init.edits ?? [])],
    images: [...(init.images ?? new Map())].map(([id, bytes]) => ({ id, bytes })),
    complete: init.complete ?? true,
    adjudicated: { ...(init.adjudicated ?? {}) },
    facts: [...(init.facts ?? [])],
    rulings: [...(init.rulings ?? [])]
  }
}

/**
 * Validate and normalize a stored record, upgrading older versions.
 *
 * Throws rather than returning a half-built run. A saved transcription is the
 * one thing here the user paid for; quietly handing back an empty or partial
 * one would look like the book had been read and produce a book with holes in
 * it. Refusing loudly sends them to a re-run, which costs money but is correct.
 */
export function migrateSavedRun(raw: unknown): SavedRun {
  if (!isObject(raw)) {
    throw new Error('Saved transcription is not an object.')
  }

  const version = num(raw['schemaVersion'], 0)
  if (version > CURRENT_SCHEMA_VERSION) {
    throw new Error(
      `Saved transcription is version ${version}, newer than this app understands ` +
        `(${CURRENT_SCHEMA_VERSION}). Update the app, or transcribe the book again.`
    )
  }
  // v1–4 came from the desktop application and hold page images and a Markdown
  // intermediate rather than a transcription — there is genuinely nothing in
  // one to restore. v5 is a browser run that predates the proof step, which is
  // a complete transcription with no corrections on it, so it upgrades.
  if (version < 5) {
    throw new Error(
      `Saved transcription is version ${version}, which the desktop application wrote. ` +
        'It holds page images and a Markdown intermediate rather than a transcription, ' +
        'so there is nothing here to restore.'
    )
  }

  const transcriptions = raw['transcriptions']
  if (!Array.isArray(transcriptions) || transcriptions.length === 0) {
    throw new Error('Saved transcription contains no pages.')
  }

  const rawUsage = isObject(raw['usage']) ? raw['usage'] : {}
  const rawFailures = Array.isArray(raw['failures']) ? raw['failures'] : []

  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    key: str(raw['key'], ''),
    fileName: str(raw['fileName'], 'a book'),
    savedAt: str(raw['savedAt'], new Date(0).toISOString()),
    pageCount: num(raw['pageCount'], transcriptions.length),
    // Never inherited from `pageCount`: a record written before v11 cannot say
    // which of the two things that number meant, and a wrong length here is
    // what makes a barely-started book report itself finished.
    leafCount: num(raw['leafCount'], 0),
    // Inline markup is converted on the way back in, not only on the way out
    // of the model. A book transcribed before that conversion existed is sitting
    // in storage with `<em>` in its text, and it was paid for — healing it here
    // costs nothing and means nobody has to buy the same pages twice to stop
    // their edition printing angle brackets.
    transcriptions: (transcriptions as PageTranscription[]).map((page) => ({
      ...page,
      blocks: page.blocks.map((b) => normalizeMarkup(b))
    })),
    failures: rawFailures.filter(isObject).map((f) => ({
      pageIndex: num(f['pageIndex'], 0),
      message: str(f['message'], 'unknown failure')
    })),
    usage: {
      inputTokens: num(rawUsage['inputTokens'], 0),
      outputTokens: num(rawUsage['outputTokens'], 0),
      cacheReadTokens: num(rawUsage['cacheReadTokens'], 0)
    },
    modelId: str(raw['modelId'], 'unknown'),
    identityAnswers: isObject(raw['identityAnswers']) ? raw['identityAnswers'] : {},
    edits: parseEdits(raw['edits']),
    images: parseImages(raw['images']),
    // Anything written before v8 could only have been written by the old
    // save-at-the-end path, so it is complete by construction.
    complete: typeof raw['complete'] === 'boolean' ? raw['complete'] : true,
    adjudicated: parseAdjudicated(raw['adjudicated']),
    facts: parseFacts(raw['facts']),
    rulings: parseRulings(raw['rulings'])
  }
}

/**
 * Read the rulings back, keeping only the well-formed ones.
 *
 * Same rule as the edits, the verdicts and the bank: a malformed entry is
 * dropped rather than thrown on, because what is at stake in one bad record is
 * one decision that has to be made again, and what refusing would cost is the
 * transcription.
 *
 * `decision` and `kind` are checked against their vocabularies rather than
 * trusted — a ruling with a decision nothing recognises would sit in the file
 * settling a query in a way no code could act on, which is worse than an
 * unanswered query because it stops anyone looking.
 */
function parseRulings(raw: unknown): Ruling[] {
  if (!Array.isArray(raw)) return []
  const out: Ruling[] = []
  for (const item of raw) {
    if (!isObject(item)) continue
    const decision = RULING_DECISIONS.find((d) => d === item['decision'])
    const kind = EDITORIAL_QUERY_KINDS.find((k) => k === item['kind'])
    const quote = str(item['quote'], '')
    if (!decision || !kind || !quote) continue
    out.push({
      pageIndex: typeof item['pageIndex'] === 'number' ? item['pageIndex'] : null,
      quote,
      kind,
      decision,
      ...(typeof item['correction'] === 'string' ? { correction: item['correction'] } : {}),
      ...(typeof item['because'] === 'string' ? { because: item['because'] } : {}),
      ...(Array.isArray(item['covers'])
        ? { covers: item['covers'].filter((c): c is string => typeof c === 'string') }
        : {}),
      decidedOn: str(item['decidedOn'], new Date(0).toISOString().slice(0, 10)),
      ...(item['mention'] === true ? { mention: true } : {})
    })
  }
  return out
}

/**
 * Read the bank entries back, keeping only the well-formed ones.
 *
 * Same rule as the edits and the verdicts: a malformed entry is dropped rather
 * than thrown on. What is at stake here is one entry in a file for reading
 * later; what refusing would cost is the transcription.
 *
 * `footing` is checked against the vocabulary rather than trusted, because it
 * is the field that makes the bank usable years later — whether the book
 * *stated* a thing, implied it, or merely surrounded it — and an entry claiming
 * a footing this app does not know is worse than one that is missing.
 */
function parseFacts(raw: unknown): Fact[] {
  if (!Array.isArray(raw)) return []
  const out: Fact[] = []
  for (const item of raw) {
    if (!isObject(item)) continue
    const footing = FOOTINGS.find((f) => f === item['footing'])
    const id = str(item['id'], '')
    const title = str(item['title'], '')
    if (!footing || !id || !title) continue
    out.push({
      id,
      title,
      body: str(item['body'], ''),
      footing,
      category: str(item['category'], ''),
      tags: Array.isArray(item['tags']) ? item['tags'].filter((t) => typeof t === 'string') : [],
      blockId: str(item['blockId'], ''),
      quote: str(item['quote'], ''),
      sourcePage: typeof item['sourcePage'] === 'number' ? item['sourcePage'] : null,
      quoteVerified: item['quoteVerified'] === true,
      ...(typeof item['demotedFrom'] === 'string'
        ? { demotedFrom: FOOTINGS.find((f) => f === item['demotedFrom']) }
        : {})
    } as Fact)
  }
  return out
}

/**
 * Read back what the second reading found, keeping only well-formed entries.
 *
 * Same rule as the edit list: a malformed record is dropped rather than thrown
 * on. Losing one verdict costs a spot that has to be judged by eye — which is
 * how every spot arrived before this existed — where refusing the whole run
 * would cost the transcription.
 */
function parseAdjudicated(
  raw: unknown
): Record<string, { verdict: string; reading: string; note: string }> {
  if (!isObject(raw)) return {}
  const out: Record<string, { verdict: string; reading: string; note: string }> = {}
  for (const [id, value] of Object.entries(raw)) {
    if (!isObject(value) || typeof value['verdict'] !== 'string') continue
    out[id] = {
      verdict: value['verdict'],
      reading: str(value['reading'], ''),
      note: str(value['note'], '')
    }
  }
  return out
}

/**
 * Read back supplied pictures, keeping only entries that still have pixels.
 *
 * Same rule as the edit list: a malformed entry is dropped rather than thrown
 * on. A picture whose bytes are gone is reported by the writer as missing, and
 * the export screen says so — which is a far better outcome than refusing to
 * restore a transcription over one bad record.
 */
function parseImages(raw: unknown): { id: string; bytes: Uint8Array }[] {
  if (!Array.isArray(raw)) return []
  const out: { id: string; bytes: Uint8Array }[] = []
  for (const value of raw) {
    if (!isObject(value)) continue
    const id = str(value['id'], '')
    const bytes = value['bytes']
    if (!id) continue
    if (bytes instanceof Uint8Array) out.push({ id, bytes })
    else if (Array.isArray(bytes)) out.push({ id, bytes: Uint8Array.from(bytes as number[]) })
  }
  return out
}

/**
 * Read back an edit list from storage, keeping only what is well-formed.
 *
 * This is untrusted input — anything in IndexedDB can have been written by an
 * older build, or corrupted, or edited by hand. A malformed record is dropped
 * rather than thrown on, which is the opposite of how the transcription itself
 * is handled, and deliberately so: losing one correction costs the user one
 * correction, where refusing the whole run would cost them the thing they paid
 * for over a typo in a field they cannot see.
 */
function parseEdits(raw: unknown): BookEdit[] {
  if (!Array.isArray(raw)) return []
  const out: BookEdit[] = []
  for (const value of raw) {
    if (!isObject(value)) continue
    const blockId = str(value['blockId'], '')
    switch (value['kind']) {
      case 'text':
        if (blockId && typeof value['text'] === 'string') {
          out.push({ kind: 'text', blockId, text: value['text'] })
        }
        break
      case 'retype': {
        // Checked against the real list rather than merely being a string: an
        // unknown kind would reach the layout engine's style table and be set
        // as whatever its fallback happens to be.
        const blockKind = BLOCK_KINDS.find((k) => k === value['blockKind'])
        if (blockId && blockKind) {
          const level = value['level']
          out.push({
            kind: 'retype',
            blockId,
            blockKind,
            ...(typeof level === 'number' ? { level } : {})
          })
        }
        break
      }
      case 'drop':
        if (blockId) out.push({ kind: 'drop', blockId })
        break
      case 'insert': {
        // Same care as `retype`: the block kind is checked against the real
        // list, because an unknown one reaches the layout engine's style table
        // and is set as whatever its fallback happens to be.
        const insertId = str(value['insertId'], '')
        const after = value['afterBlockId']
        const blockKind = BLOCK_KINDS.find((k) => k === value['blockKind'])
        if (
          insertId &&
          blockKind &&
          (after === null || typeof after === 'string') &&
          typeof value['text'] === 'string'
        ) {
          const level = value['level']
          out.push({
            kind: 'insert',
            insertId,
            afterBlockId: after,
            blockKind,
            text: value['text'],
            ...(typeof level === 'number' ? { level } : {})
          })
        }
        break
      }
      case 'split':
        if (blockId && typeof value['at'] === 'number') {
          out.push({ kind: 'split', blockId, at: value['at'] })
        }
        break
      case 'merge':
        if (blockId) out.push({ kind: 'merge', blockId })
        break
      case 'image': {
        const imageId = str(value['imageId'], '')
        const after = value['afterBlockId']
        if (
          imageId &&
          (after === null || typeof after === 'string') &&
          typeof value['sourceWidth'] === 'number' &&
          typeof value['sourceHeight'] === 'number'
        ) {
          const caption = value['caption']
          out.push({
            kind: 'image',
            imageId,
            afterBlockId: after,
            sourceWidth: value['sourceWidth'],
            sourceHeight: value['sourceHeight'],
            ...(typeof caption === 'string' ? { caption } : {})
          })
        }
        break
      }
      case 'retouch': {
        const illustrationId = str(value['illustrationId'], '')
        const ops = value['ops']
        if (illustrationId && Array.isArray(ops)) {
          // Each op is checked for the shape the engine reads, and anything
          // else is dropped — an op with no `op` would reach `applyOne`'s
          // switch and silently do nothing, which is worse than not being there.
          const clean = ops.filter(
            (o): o is ImageEditOp =>
              isObject(o) && typeof o['op'] === 'string' && isObject(o['params'])
          )
          if (clean.length > 0) out.push({ kind: 'retouch', illustrationId, ops: clean })
        }
        break
      }
      case 'section': {
        const sectionId = str(value['sectionId'], '')
        const placement = value['placement']
        if (
          sectionId &&
          (placement === 'front' || placement === 'back') &&
          typeof value['title'] === 'string' &&
          typeof value['text'] === 'string'
        ) {
          out.push({
            kind: 'section',
            sectionId,
            placement,
            title: value['title'],
            text: value['text']
          })
        }
        break
      }
      case 'note': {
        const noteId = str(value['noteId'], '')
        if (
          noteId &&
          blockId &&
          typeof value['at'] === 'number' &&
          typeof value['text'] === 'string'
        ) {
          out.push({ kind: 'note', noteId, blockId, at: value['at'], text: value['text'] })
        }
        break
      }
      case 'anchor': {
        const illustrationId = str(value['illustrationId'], '')
        const after = value['afterBlockId']
        if (illustrationId && (after === null || typeof after === 'string')) {
          out.push({ kind: 'anchor', illustrationId, afterBlockId: after })
        }
        break
      }
    }
  }
  return out
}

/** "3 days ago" — plain enough to be read at a glance in the resume offer. */
export function describeAge(savedAt: string, now: Date = new Date()): string {
  const then = new Date(savedAt).getTime()
  if (!Number.isFinite(then)) return 'at some point'

  const minutes = Math.floor((now.getTime() - then) / 60000)
  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes} minute${minutes === 1 ? '' : 's'} ago`

  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours} hour${hours === 1 ? '' : 's'} ago`

  const days = Math.floor(hours / 24)
  if (days < 30) return `${days} day${days === 1 ? '' : 's'} ago`

  const months = Math.floor(days / 30)
  return `${months} month${months === 1 ? '' : 's'} ago`
}
