/**
 * The saved transcription run — what is worth keeping between sittings.
 *
 * Everything this app does is free except one step. Rendering, OCR, the
 * lexicon, assembly, layout and the PDF all cost nothing but time and can be
 * redone at will. The vision pass costs the user real money, once, per page.
 * So that is the only thing persisted: **the expensive output, keyed to the
 * file it came from.** Reopening the same book re-runs the free half and skips
 * the paid half.
 *
 * Deliberately *not* stored:
 *
 * - **The PDF itself.** A scan runs to hundreds of megabytes and the user
 *   already has it. Requiring it back on resume costs them one file picker and
 *   buys full fidelity: the word crops and page thumbnails the review gates
 *   show are regenerated by the free pass, so nothing is missing.
 * - **The API key.** It lives in its own store and must never travel with a
 *   book (see `platform/browser/settings`).
 * - **Anything derivable.** The assembled document, the findings summary, the
 *   layout — all pure functions of the transcriptions, so storing them would
 *   only create a second copy that could disagree with the first.
 *
 * Pure: types, versioning and migration. The store is in the platform layer.
 */
import { BLOCK_KINDS, type PageTranscription } from '@core/transcribe'
import type { BookEdit } from '@core/edits'

/**
 * Current schema version. Bump and extend `migrateSavedRun` on any shape change.
 *
 * Versions 1–4 were the desktop application's `project.json` — a manifest of
 * page images, a Markdown intermediate, a coordinate map and non-destructive
 * image edits, none of which the browser app produces. Nothing ever wrote one
 * from a browser, so this does not migrate them; it recognises them and says so.
 *
 * v5 → v6 added the proofreading corrections, and v6 → v7 the pixels of any
 * pictures the editor supplied. Neither damages an older run — each is a
 * complete transcription that simply has none of the newer thing on it yet — so
 * both upgrade in place rather than being refused. That distinction is the
 * whole reason a migration exists instead of a version check.
 */
export const CURRENT_SCHEMA_VERSION = 7

/** A page the model could not read at all. Mirrors the runner's `PageFailure`. */
export interface SavedFailure {
  pageIndex: number
  message: string
}

/** Tokens spent, so the resume offer can say what re-running would cost again. */
export interface SavedUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
}

export interface SavedRun {
  schemaVersion: number
  /** Identifies the file this run belongs to — see `fileKey`. */
  key: string
  /** For showing the user which book this is. */
  fileName: string
  /** ISO timestamp, so the offer can say how old the run is. */
  savedAt: string
  pageCount: number
  /** The expensive part. */
  transcriptions: PageTranscription[]
  failures: SavedFailure[]
  usage: SavedUsage
  /** The model that read the pages, for the record. */
  modelId: string
  /**
   * The identity gate's answers, kept because they *shaped* this run — the
   * orthography choice and the long-s decision went into the prompt. Restoring
   * them stops the user silently changing an answer that can no longer take
   * effect on text the model has already produced.
   */
  identityAnswers: Record<string, unknown>
  /**
   * Corrections made at the proof step.
   *
   * Stored for the same reason the transcription is: they are the other thing
   * in this app the user cannot get back for free. Everything else — the
   * render, the OCR, the lexicon, the assembly, the layout — is regenerated
   * from the scan on the way back in, but an hour spent reading a book against
   * its scan is an hour, and a refresh must not cost it.
   */
  edits: BookEdit[]
  /**
   * Pixels for the pictures the editor supplied, by illustration id.
   *
   * Unlike everything else about an illustration, these cannot be re-derived
   * from anything the app has: a crop can be cut out of the scan again, but a
   * portrait the editor chose off their own disk is gone with the tab. Stored
   * as bytes because IndexedDB clones a `Uint8Array` natively, and bounded at
   * decode time so a phone photograph does not fill the store on its own.
   */
  images: { id: string; bytes: Uint8Array }[]
}

/** The facts the resume question needs, without loading the whole run. */
export interface SavedRunSummary {
  key: string
  fileName: string
  savedAt: string
  pageCount: number
  failedPages: number
  modelId: string
  usage: SavedUsage
}

export function summarize(run: SavedRun): SavedRunSummary {
  return {
    key: run.key,
    fileName: run.fileName,
    savedAt: run.savedAt,
    pageCount: run.pageCount,
    failedPages: run.failures.length,
    modelId: run.modelId,
    usage: run.usage
  }
}

/**
 * A stable identity for the file a run belongs to.
 *
 * Name, size and modification time — not a hash of the contents. Hashing would
 * mean reading a few hundred megabytes into memory to answer a question that
 * only ever means "is this the same file the user had open before", and this
 * codebase is careful never to hold a whole book at once. The cost of being
 * wrong is small in both directions: a false miss offers a re-run the user can
 * decline, and a false hit is not reachable without deliberately crafting a
 * different file with an identical name, size and timestamp.
 */
export function fileKey(file: { name: string; size: number; lastModified: number }): string {
  // NUL joins the parts because it is the one byte a file name cannot
  // contain, so no name can be crafted to collide with a different file.
  return [file.name, file.size, file.lastModified].join('\u0000')
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function num(v: unknown, fallback: number): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback
}

function str(v: unknown, fallback: string): string {
  return typeof v === 'string' ? v : fallback
}

/** Build a run record from a finished transcription. */
export function createSavedRun(init: {
  key: string
  fileName: string
  pageCount: number
  transcriptions: readonly PageTranscription[]
  failures: readonly SavedFailure[]
  usage: SavedUsage
  modelId: string
  identityAnswers: Record<string, unknown>
  edits?: readonly BookEdit[]
  images?: ReadonlyMap<string, Uint8Array>
  savedAt?: string
}): SavedRun {
  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    key: init.key,
    fileName: init.fileName,
    savedAt: init.savedAt ?? new Date().toISOString(),
    pageCount: init.pageCount,
    transcriptions: [...init.transcriptions],
    failures: [...init.failures],
    usage: init.usage,
    modelId: init.modelId,
    identityAnswers: init.identityAnswers,
    edits: [...(init.edits ?? [])],
    images: [...(init.images ?? new Map())].map(([id, bytes]) => ({ id, bytes }))
  }
}

/**
 * Validate and normalize a stored record, upgrading older versions.
 *
 * Throws rather than returning a half-built run. A saved transcription is the
 * one thing here the user paid for; quietly handing back an empty or partial
 * one would look like the book had been read and produce a book with holes in
 * it. Refusing loudly sends them to a re-run, which costs money but is correct.
 */
export function migrateSavedRun(raw: unknown): SavedRun {
  if (!isObject(raw)) {
    throw new Error('Saved transcription is not an object.')
  }

  const version = num(raw['schemaVersion'], 0)
  if (version > CURRENT_SCHEMA_VERSION) {
    throw new Error(
      `Saved transcription is version ${version}, newer than this app understands ` +
        `(${CURRENT_SCHEMA_VERSION}). Update the app, or transcribe the book again.`
    )
  }
  // v1–4 came from the desktop application and hold page images and a Markdown
  // intermediate rather than a transcription — there is genuinely nothing in
  // one to restore. v5 is a browser run that predates the proof step, which is
  // a complete transcription with no corrections on it, so it upgrades.
  if (version < 5) {
    throw new Error(
      `Saved transcription is version ${version}, which the desktop application wrote. ` +
        'It holds page images and a Markdown intermediate rather than a transcription, ' +
        'so there is nothing here to restore.'
    )
  }

  const transcriptions = raw['transcriptions']
  if (!Array.isArray(transcriptions) || transcriptions.length === 0) {
    throw new Error('Saved transcription contains no pages.')
  }

  const rawUsage = isObject(raw['usage']) ? raw['usage'] : {}
  const rawFailures = Array.isArray(raw['failures']) ? raw['failures'] : []

  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    key: str(raw['key'], ''),
    fileName: str(raw['fileName'], 'a book'),
    savedAt: str(raw['savedAt'], new Date(0).toISOString()),
    pageCount: num(raw['pageCount'], transcriptions.length),
    transcriptions: transcriptions as PageTranscription[],
    failures: rawFailures.filter(isObject).map((f) => ({
      pageIndex: num(f['pageIndex'], 0),
      message: str(f['message'], 'unknown failure')
    })),
    usage: {
      inputTokens: num(rawUsage['inputTokens'], 0),
      outputTokens: num(rawUsage['outputTokens'], 0),
      cacheReadTokens: num(rawUsage['cacheReadTokens'], 0)
    },
    modelId: str(raw['modelId'], 'unknown'),
    identityAnswers: isObject(raw['identityAnswers']) ? raw['identityAnswers'] : {},
    edits: parseEdits(raw['edits']),
    images: parseImages(raw['images'])
  }
}

/**
 * Read back supplied pictures, keeping only entries that still have pixels.
 *
 * Same rule as the edit list: a malformed entry is dropped rather than thrown
 * on. A picture whose bytes are gone is reported by the writer as missing, and
 * the export screen says so — which is a far better outcome than refusing to
 * restore a transcription over one bad record.
 */
function parseImages(raw: unknown): { id: string; bytes: Uint8Array }[] {
  if (!Array.isArray(raw)) return []
  const out: { id: string; bytes: Uint8Array }[] = []
  for (const value of raw) {
    if (!isObject(value)) continue
    const id = str(value['id'], '')
    const bytes = value['bytes']
    if (!id) continue
    if (bytes instanceof Uint8Array) out.push({ id, bytes })
    else if (Array.isArray(bytes)) out.push({ id, bytes: Uint8Array.from(bytes as number[]) })
  }
  return out
}

/**
 * Read back an edit list from storage, keeping only what is well-formed.
 *
 * This is untrusted input — anything in IndexedDB can have been written by an
 * older build, or corrupted, or edited by hand. A malformed record is dropped
 * rather than thrown on, which is the opposite of how the transcription itself
 * is handled, and deliberately so: losing one correction costs the user one
 * correction, where refusing the whole run would cost them the thing they paid
 * for over a typo in a field they cannot see.
 */
function parseEdits(raw: unknown): BookEdit[] {
  if (!Array.isArray(raw)) return []
  const out: BookEdit[] = []
  for (const value of raw) {
    if (!isObject(value)) continue
    const blockId = str(value['blockId'], '')
    switch (value['kind']) {
      case 'text':
        if (blockId && typeof value['text'] === 'string') {
          out.push({ kind: 'text', blockId, text: value['text'] })
        }
        break
      case 'retype': {
        // Checked against the real list rather than merely being a string: an
        // unknown kind would reach the layout engine's style table and be set
        // as whatever its fallback happens to be.
        const blockKind = BLOCK_KINDS.find((k) => k === value['blockKind'])
        if (blockId && blockKind) {
          const level = value['level']
          out.push({
            kind: 'retype',
            blockId,
            blockKind,
            ...(typeof level === 'number' ? { level } : {})
          })
        }
        break
      }
      case 'drop':
        if (blockId) out.push({ kind: 'drop', blockId })
        break
      case 'split':
        if (blockId && typeof value['at'] === 'number') {
          out.push({ kind: 'split', blockId, at: value['at'] })
        }
        break
      case 'merge':
        if (blockId) out.push({ kind: 'merge', blockId })
        break
      case 'image': {
        const imageId = str(value['imageId'], '')
        const after = value['afterBlockId']
        if (
          imageId &&
          (after === null || typeof after === 'string') &&
          typeof value['sourceWidth'] === 'number' &&
          typeof value['sourceHeight'] === 'number'
        ) {
          const caption = value['caption']
          out.push({
            kind: 'image',
            imageId,
            afterBlockId: after,
            sourceWidth: value['sourceWidth'],
            sourceHeight: value['sourceHeight'],
            ...(typeof caption === 'string' ? { caption } : {})
          })
        }
        break
      }
      case 'note': {
        const noteId = str(value['noteId'], '')
        if (
          noteId &&
          blockId &&
          typeof value['at'] === 'number' &&
          typeof value['text'] === 'string'
        ) {
          out.push({ kind: 'note', noteId, blockId, at: value['at'], text: value['text'] })
        }
        break
      }
      case 'anchor': {
        const illustrationId = str(value['illustrationId'], '')
        const after = value['afterBlockId']
        if (illustrationId && (after === null || typeof after === 'string')) {
          out.push({ kind: 'anchor', illustrationId, afterBlockId: after })
        }
        break
      }
    }
  }
  return out
}

/** "3 days ago" — plain enough to be read at a glance in the resume offer. */
export function describeAge(savedAt: string, now: Date = new Date()): string {
  const then = new Date(savedAt).getTime()
  if (!Number.isFinite(then)) return 'at some point'

  const minutes = Math.floor((now.getTime() - then) / 60000)
  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes} minute${minutes === 1 ? '' : 's'} ago`

  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours} hour${hours === 1 ? '' : 's'} ago`

  const days = Math.floor(hours / 24)
  if (days < 30) return `${days} day${days === 1 ? '' : 's'} ago`

  const months = Math.floor(days / 30)
  return `${months} month${months === 1 ? '' : 's'} ago`
}
