/**
 * Page roles (SPEC §7 front/back matter).
 *
 * OCR emits a flat character stream with no sense of what a page *is* — a title
 * page and a body page look identical to it. The vision pass classifies each
 * page instead, and that classification drives a decision the whole reprint
 * depends on:
 *
 *   Most front matter is **replaced, not transcribed.** You are the publisher of
 *   this edition, so the original's title page, imprint, and copyright notice
 *   are *sources of data* (title, author, original year), not text to carry
 *   through. The scanned TOC and index are worse than useless — their page
 *   numbers refer to the original pagination and will be wrong in your edition.
 *
 * Pure data + rules; no model calls, no I/O.
 */

export type PageRole =
  // — front matter —
  | 'half-title'
  | 'title-page'
  | 'copyright'
  | 'dedication'
  | 'epigraph'
  | 'preface'
  | 'table-of-contents'
  | 'list-of-illustrations'
  // — body —
  | 'chapter-opening'
  | 'body'
  | 'part-divider'
  | 'plate'
  // — back matter —
  | 'index'
  | 'appendix'
  | 'glossary'
  | 'colophon'
  // — neither —
  | 'blank'
  /**
   * A leaf the scanning library inserted, not a leaf of the book.
   *
   * Every archive.org scan carries one — "Digitized for X by the Internet
   * Archive in 2007" — and it is neither the book's colophon nor blank. Read as
   * a colophon it printed as a page of its own in a reprint that has nothing to
   * do with the scanning, and dropped as blank the record of where the copy
   * came from went with it. It is discarded from the body, and the credit
   * belongs on the copyright page, where `sourceNotice` sets it.
   */
  | 'digitization-notice'
  | 'unknown'

/** What the pipeline does with a page's text once its role is known. */
export type PageDisposition =
  /** Transcribe into the book body. */
  | 'transcribe'
  /** Don't transcribe; mine it for metadata that fills our own templates. */
  | 'extract-metadata'
  /** Drop entirely — regenerated by us, or carries stale pagination. */
  | 'discard'
  /** Keep the text but set it apart from the main flow. */
  | 'transcribe-aside'

const DISPOSITIONS: Record<PageRole, PageDisposition> = {
  // Mined for metadata, never transcribed verbatim.
  'half-title': 'extract-metadata',
  'title-page': 'extract-metadata',
  copyright: 'extract-metadata',
  // Regenerated from confirmed structure — the scanned versions carry the
  // ORIGINAL edition's page numbers and would be wrong in ours.
  'table-of-contents': 'discard',
  'list-of-illustrations': 'discard',
  index: 'discard',
  blank: 'discard',
  'digitization-notice': 'discard',
  // Real content, but set apart from the main narrative flow.
  dedication: 'transcribe-aside',
  epigraph: 'transcribe-aside',
  colophon: 'transcribe-aside',
  // Straight into the body.
  preface: 'transcribe',
  'chapter-opening': 'transcribe',
  body: 'transcribe',
  'part-divider': 'transcribe',
  plate: 'transcribe',
  appendix: 'transcribe',
  glossary: 'transcribe',
  unknown: 'transcribe'
}

/** What to do with a page of this role. */
export function dispositionFor(role: PageRole): PageDisposition {
  return DISPOSITIONS[role]
}

const FRONT_MATTER: ReadonlySet<PageRole> = new Set<PageRole>([
  'half-title',
  'title-page',
  'copyright',
  'dedication',
  'epigraph',
  'preface',
  'table-of-contents',
  'list-of-illustrations'
])

export function isFrontMatter(role: PageRole): boolean {
  return FRONT_MATTER.has(role)
}

/** Human-facing label for the review UI. */
export function roleLabel(role: PageRole): string {
  return role
    .split('-')
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join(' ')
}

/**
 * Bibliographic data mined from the original front matter. Pre-fills our own
 * templated title/copyright pages — every field is confirmed by the user at the
 * front-matter gate, never used blind.
 */
export interface BookMetadata {
  title: string | null
  subtitle: string | null
  author: string | null
  /** Year of the ORIGINAL edition (for the "originally published" line). */
  originalYear: string | null
  originalPublisher: string | null
  originalPlace: string | null
  /** Translator/editor credits found on the title page. */
  contributors: string[]
}

export function emptyBookMetadata(): BookMetadata {
  return {
    title: null,
    subtitle: null,
    author: null,
    originalYear: null,
    originalPublisher: null,
    originalPlace: null,
    contributors: []
  }
}

/** One page's classification, produced by the vision pass. */
export interface PageClassification {
  pageIndex: number
  role: PageRole
  /**
   * The model's stated confidence, 0–1. Honest tiering (SPEC §4): this is a
   * self-report, so it gates *review ordering* only — never whether a page is
   * checked at all.
   */
  selfReportedConfidence: number
  /** Text identified as running head / folio, stripped from the body flow. */
  furniture?: { runningHead?: string; folio?: string }
}

/**
 * Running heads and page numbers repeat on every body page. Left in, they
 * interleave into paragraphs; this reports what was stripped so the user can
 * see the pass didn't silently eat real text.
 */
export function strippedFurniture(pages: readonly PageClassification[]): {
  runningHeads: string[]
  folioCount: number
} {
  const heads = new Set<string>()
  let folios = 0
  for (const p of pages) {
    if (p.furniture?.runningHead) heads.add(p.furniture.runningHead)
    if (p.furniture?.folio) folios++
  }
  return { runningHeads: [...heads].sort(), folioCount: folios }
}

/**
 * Partition classified pages by what the pipeline should do with each.
 * Drives the front-matter review gate and the body assembly.
 */
export function partitionByDisposition(
  pages: readonly PageClassification[]
): Record<PageDisposition, number[]> {
  const out: Record<PageDisposition, number[]> = {
    transcribe: [],
    'extract-metadata': [],
    discard: [],
    'transcribe-aside': []
  }
  for (const p of pages) out[dispositionFor(p.role)].push(p.pageIndex)
  for (const k of Object.keys(out) as PageDisposition[]) out[k].sort((a, b) => a - b)
  return out
}
